const data_exam = [
  {
    name_exam: "Giữa kì 1",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 1,
    time_exam: 120,
    time_start: "8h/ 02-03-2023",
    status: 0,
  },
  {
    name_exam: "Giữa kì 1",
    subject: "Văn",
    type: "Tự luận",
    class: 1,
    time_exam: 180,
    time_start: "9h/ 03-03-2023",
    status: 1,
  },
  {
    name_exam: "Giữa kì 1",
    subject: "Khoa học",
    type: "Trắc nghiệm",
    class: 2,
    time_exam: 90,
    time_start: "10h/ 04-03-2023",
    status: 2,
  },
  {
    name_exam: "Cuối kì 1",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 3,
    time_exam: 120,
    time_start: "14h/ 05-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 1",
    subject: "Văn",
    type: "Tự luận",
    class: 4,
    time_exam: 180,
    time_start: "8h/ 06-03-2023",
    status: 1,
  },
  {
    name_exam: "Cuối kì 1",
    subject: "Khoa học",
    type: "Trắc nghiệm",
    class: 5,
    time_exam: 90,
    time_start: "9h/ 07-03-2023",
    status: 2,
  },
  {
    name_exam: "Giữa kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 6,
    time_exam: 120,
    time_start: "10h/ 08-03-2023",
    status: 0,
  },
  {
    name_exam: "Giữa kì 2",
    subject: "Văn",
    type: "Tự luận",
    class: 7,
    time_exam: 180,
    time_start: "14h/ 09-03-2023",
    status: 1,
  },
  {
    name_exam: "Giữa kì 2",
    subject: "Khoa học",
    type: "Trắc nghiệm",
    class: 8,
    time_exam: 90,
    time_start: "8h/ 10-03-2023",
    status: 2,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  ,
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
  {
    name_exam: "Cuối kì 2",
    subject: "Toán",
    type: "Trắc nghiệm",
    class: 9,
    time_exam: 120,
    time_start: "9h/ 11-03-2023",
    status: 0,
  },
];
